### ISSUE TITLE
marker.yaml

### ISSUE THREAD

**Issue by jjia1** [joschif/snapseed#3]
Can you provide an example of a hierarchical marker.yaml file to use snapseed? From the paper in the Methods section:

> annotate() for non-hierarchical annotation of a list of cell types with defined marker genes, annotate_hierarchy() for annotating more complex, manually defined cell type hierarchies and find_markers() for fast discovery of cluster-specific features

Is the structure of the .yaml file supposed to be like this?

```
Celltype: Cell 1
  Markers:
    Marker 1: M1
    Marker 2: M2
Celltype: Cell 2
```

**Comment by hassansaei** [comment]
> Can you provide an example of a hierarchical marker.yaml file to use snapseed? From the paper in the Methods section:
> 
> > annotate() for non-hierarchical annotation of a list of cell types with defined marker genes, annotate_hierarchy() for annotating more complex, manually defined cell type hierarchies and find_markers() for fast discovery of cluster-specific features
> 
> Is the structure of the .yaml file supposed to be like this?
> 
> ```
> Celltype: Cell 1
>   Markers:
>     Marker 1: M1
>     Marker 2: M2
> Celltype: Cell 2
> ```

The **marker.yaml** file is provided in the supplementary of the paper **"An integrated transcriptomic cell atlas of human neural organoids"**. You can download it from this link: https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-024-08172-8/MediaObjects/41586_2024_8172_MOESM1_ESM.zip

**Comment by joschif** [comment]
Hi @jjia1 and @hassansaei, the structure of the dict is supposed to be something like this:

```
neural_progenitor_cell:
  marker_genes: [SOX2, VIM, NES]
  subtypes: 
    glioblast:
      marker_genes: [HOPX, BCAN, TNC] 
    telencephalic_npc:
      marker_genes: [FOXG1]
      subtypes: 
        dorsal_npc:
          marker_genes: [EMX1]
        hippocampal_npc:
          marker_genes: [GABRA2, GABRB1] 
        ventral_npc:
          marker_genes: [DLX2]
```

the marker list in the supplement of out paper that @hassansaei pointed to should be a full example for that and is what we used for annotation.
